/** @file
 *	@brief	Timer System Service implementation.
 *
 *	Description:
 *	The Timer System Service provides a simple interface to manage the Timer modules
 *	on Microchip micro controllers.  This file implements the core interface routines
 *	for the System Timer Service.
 *	While building the SYS TMR from source, ALWAYS use this file in the build.
 *
 *
 *	@note	This file is an as-needed COPY of the file created by Microchip's Harmony Configurator,
 *	v2.04, and/or the tool-created support files (e.g., Peripheral Libs) supplied as part of the
 *	MHC eco system. We have NO intention of stealing code or technology, or of claiming undue
 *	credit. This file is here ONLY during the buildup of support for the PIC32 MZ2048 EFM 144
 *	Starter Kit, what we call the "MZ EZ" board. Eventually, I hope to link directly to Harmony's
 *	code, in a way that allows different target architectures
 *
 *	Anyway, because this is a copy of code generated by a tool owned by Microchip, there is
 *	attribution here but no copyright notice.
 *
 *
 *	Original:
 *	Created on: Dec 25, 2017
 *	Author: kbecker
 *
 *	Current:
 *	$Revision: $
 *	$Date: $
 */

// ============================================================================
// ----	Include Files ---------------------------------------------------------
// ============================================================================

// ----	System Headers --------------------------

// ----	Project Headers -------------------------
//#include "system/tmr/src/sys_tmr_local.h"

// ----	Module Headers --------------------------


// ============================================================================
// ----	Constants -------------------------------------------------------------
// ============================================================================

// ============================================================================
// ----	Type Definitions ------------------------------------------------------
// ============================================================================

// ============================================================================
// ----	Global Variables ------------------------------------------------------
// ============================================================================

// ============================================================================
// ----	Module-level Variables ------------------------------------------------
// ============================================================================
static char const * const sys_tmr_RevString = "$Revision: 0123 $";

/* System timer instance */
//static SYS_TMR_OBJECT           sSysTmrObject = { 0 };

/* Client object array */
//static SYS_TMR_CLIENT_OBJECT    sClientObjects [ SYS_TMR_MAX_CLIENT_OBJECTS ];


// ============================================================================
// ----	Private Prototypes ----------------------------------------------------
// ============================================================================

/* OSAL user protection
 *
 * Summary:
 * 	Enforces the user threads protection
 *
 * Description:
 *	Protects against multiple users using concurrently the TMR service.
 *	For efficiency reasons, there is NO PROTECTION for each API call except
 *	when creating and deleting new timer clients!
 *	What it means is that:
 *	- A client timer cannot be used concurrently from multiple threads!
 *	It's ok to pass a handle from one thread to another as long as
 *	there's is no access from more than one thread at a time
 *
 * Remarks:
 *	None.
 */
//static __inline__ bool
//_UserGblLockCreate(void)
//{
//    // create the shared Data Lock
//    return OSAL_SEM_Create(&sSysTmrObject.userSem, OSAL_SEM_TYPE_BINARY, 1, 1) == OSAL_RESULT_TRUE;
//}


// ============================================================================
// ----	Public Functions ------------------------------------------------------
// ============================================================================
