/** @file
 *	@brief	Initialize the MCU.
 *
 *	Description:
 *
 *	Copyright (c) 2018 Kevin L. Becker. All rights reserved.
 *
 *	Original:
 *	Created on: Jan 3, 2018
 *	Author: kbecker
 *
 *	Current:
 *	$Revision: $
 *	$Date: $
 */

// ============================================================================
// ----	Include Files ---------------------------------------------------------
// ============================================================================

#include "projcfg.h"

// ----	System Headers --------------------------
#include <stdbool.h>				/* type bool + true, false */

// ----	Project Headers -------------------------

// ----	Module Headers --------------------------
#include "cwsw_arch.h"


// ============================================================================
// ----	Constants -------------------------------------------------------------
// ============================================================================

// ============================================================================
// ----	Type Definitions ------------------------------------------------------
// ============================================================================

// ============================================================================
// ----	Global Variables ------------------------------------------------------
// ============================================================================

// ============================================================================
// ----	Module-level Variables ------------------------------------------------
// ============================================================================
static char const * const cwsw_arch_RevString = "$Revision: 0123 $";

static bool initialized = false;


// ============================================================================
// ----	Private Prototypes ----------------------------------------------------
// ============================================================================
#if (USE_SYS_CLK == true)
#include "system/clk/sys_clk.h"		/* todo: make "system/clk" when eclipse symlinks are removed */
WEAK void
SYS_CLK_Initialize ( const SYS_CLK_INIT *clkInit )
{
	/* NOTE: In the Microchip ecosystem, this function is located in the Harmony framework.
	 * i'm not sure yet how to link into that system, without requiring the user to install
	 * Framework at a known position.
	 *
	 * todo: investigate symlinking the MHC framework folder - in theory, this might work, because
	 * MHC already requires installation on the same drive / parent directory as the projects
	 * using MHC.
	 */

	UNUSED(clkInit);
}

#else
#define SYS_CLK_Initialize(a)			do { UNUSED(a); } while(0)

#endif

#if (USE_SYS_DEVCON == true)
WEAK SYS_MODULE_OBJ
SYS_DEVCON_Initialize( const SYS_MODULE_INDEX index, const SYS_MODULE_INIT * const init )
{
	/* NOTE: In the Microchip ecosystem, this function is located in the code generated by the
	 * Harmony code generator. because the caller, Init(Cwsw_Arch), is located in a reusable
	 * library, i'm not yet certain of the best way to leverage this.
	 *
	 * todo: investigate symlinking the generated code
	 */
}
#else
#define SYS_DEVCON_Initialize(a, b)		do { UNUSED(a); UNUSED(b); } while(0)
#define SYS_DEVCON_PerformanceConfig(a)	do { UNUSED(a); } while(0)

#endif

#if (USE_SYS_PORTS == true)
	#include "system/ports/sys_ports.h"

#else
#define SYS_PORTS_Initialize()			do {} while(0)

#endif


// ============================================================================
// ----	Public Functions ------------------------------------------------------
// ============================================================================

uint16_t
Cwsw_Arch__Init(void)
{
	UNUSED(cwsw_arch_RevString);
	// for desktop use, there's really not much to do here.

    /* Core Processor Initialization */
	SYS_CLK_Initialize( NULL );
	SYS_DEVCON_Initialize(0, NULL);
	SYS_DEVCON_PerformanceConfig(0);
	SYS_PORTS_Initialize();

	initialized = true;
	return 0;

}


bool
Cwsw_Arch__Get_Initialized(void)
{
	return initialized;
}

// ====	COMPONENT DOCUMENTATION ============================================== {
#if defined(IN_DOXY)				/* { */
/**	\page Arch_Head Reusable Component : MCU Architecture Support
 *	@tableofcontents
 * 		@subpage Arch_Introduction \n
 * 		@subpage Arch_Design \n
 * 		@subpage Arch_Integration \n
 * 		@subpage StateEngine \n
 * 		@subpage Arch_srs \n
 */

/**	\page Arch_Introduction					Introduction to the Architecture reusable component
 *	@tableofcontents
 *	This chapter briefly describes the design and implementation of the Architecture reusable
 *	component member of the CWSW library.
 *
 *	This chapter also briefly describes the integration of this feature into the larger code base
 *	of the user software project.
 *
 *	The intended audience of this document is any software engineer who uses the CWSW library and
 *	wants to add support for one (or more) of the supported architectures.
 *
 *	\section arch_directory_layout			Directory Layout
 *	The Includes structure here is slightly different than in other CWSW components designed for
 *	reuse / multiple deployments.
 *
 *	In most CWSW components, the main API is published at the root of the component folder;
 *	any local-to-component headers are located within appropriate subfolders.
 *
 *	For this component, the main API is at the root of the architecture-specific folder.
 *	While there is an API file that exposes all APIs common to all architectures located at the
 *	component root, this is not intended to be used by projects that use the Architecture-Support
 *	component.
 *
 *
 *	\section arch_related_docs				Applicable Documents
 *	TBD
 *
 *	\section arch_terms						Terms, Acronyms, Abbreviations
 */

/**	\page Arch_Design						Architecture Subsystem Design
 *	@tableofcontents
 *		@subpage Arch_Responsibilities \n
 *		@subpage Arch_Constraints \n
 *		@subpage Arch_Interactions \n
 *		@subpage Arch_Composition \n
 *		@subpage Arch_Resources \n
 *		@subpage Arch_Interfaces \n
 *		@subpage Arch_Main_Obj_Diag \n
 *		@subpage Arch_Seq_Diag_Fail \n
 *		@subpage Arch_Dsm \n
 */

	/**	@page Arch_Responsibilities			Component Responsibilities
	 *	@tableofcontents
	 * 	The Architecture component manages all aspects of the MCU. In some cases, one Component may
	 * 	be configured to handle multiple variants of the MCU; however, in most cases, there will be
	 * 	one Arch component per MCU variant.
	 */

	/**	@page Arch_Constraints				Constraints Imposed Upon Component
	 *	@tableofcontents
	 *	-	TBD. Should be at the "bottom" of the dependency tree, except for libraries such as the
	 *		CWSW Library.
	 */

	/**	\page Arch_Interactions				Interactions
	 *	@tableofcontents
	 *	-	TBD
	 */

	/**	\page Arch_Resources        	   	Resources
	 *	@tableofcontents
	 *	TBD
	 */

	/**	\page Arch_Interfaces          		Interfaces
	 *	@tableofcontents
	 *	In this module, we are introducing several proposed new interfaces.
	 *
	 *	@subpage Arch_interfaces_headers	\n
	 *	@subpage Arch_interfaces_abstraction
	 */

	/**	\page Arch_interfaces_abstraction	Abstraction Macro Interfaces
	 *	@tableofcontents
	 *	The motivation for the first of the two following proposals, comes from the Dish desire to
	 *	avoid placing direct references within a module, to other modules.  This is motivated by a
	 *	desire to improve reusability.  Since fulfilling this abstraction requires macros in the
	 *	PRV headers, we are proposing a generalization of this abstraction.
	 *
	 *	@subpage Get_Macro \n
	 *	@subpage Set_Macro \n
	 *	@subpage Notify_Macro \n
	 */

	/**	\page Arch_Seq_Diag_Fail	        CLSA Failures Sequence Diagram
	 *	@tableofcontents
     *	\image html sdCLSA__FailureCheck.jpg "Failures Detection - Details TBD"
	 */

/**	@page Arch_Integration					Integrating the Reusable Component
 *	@tableofcontents
 */

#endif								/* } */
// ==== /COMPONENT DOCUMENTATION ============================================= }

