/** @file
 *	@brief	Ports Peripheral Library Interface header for Ports function definitions.
 *
 *	Description:
 *	This header file contains the function prototypes and definitions of
 *	the data types and constants that make up the interface to the Ports
 *	Peripheral Library for all families of Microchip microcontrollers. The
 *	definitions in this file are common to the Ports peripheral.
 *
 *
 *	@note	This file is an as-needed COPY of the file created by Microchip's Harmony Configurator,
 *	v2.04, and/or the tool-created support files (e.g., Peripheral Libs) supplied as part of the
 *	MHC eco system. We have NO intention of stealing code or technology, or of claiming undue
 *	credit. This file is here ONLY during the buildup of support for the PIC32 MZ2048 EFM 144
 *	Starter Kit, what we call the "MZ EZ" board. Eventually, I hope to link directly to Harmony's
 *	code, in a way that allows different target architectures
 *
 *	Anyway, because this is a copy of code generated by a tool owned by Microchip, there is
 *	attribution here but no copyright notice.
 *
 *
 *	Original:
 *	Created on: Dec 25, 2017
 *	Author: kbecker
 *
 *	Current:
 *	$Revision: $
 *	$Date: $
 */

#ifndef PLIB_PORTS_H_
#define PLIB_PORTS_H_

#ifdef	__cplusplus
extern "C" {
#endif

// ============================================================================
// ----	Include Files ---------------------------------------------------------
// ============================================================================

#include "projcfg.h"

// ----	System Headers --------------------------

// ----	Project Headers -------------------------

// ----	Module Headers --------------------------


// ============================================================================
// ----	Constants -------------------------------------------------------------
// ============================================================================
#define PLIB_PORTS_H__REVSTRING "$Revision: 0123 $"


// ============================================================================
// ----	Type Definitions ------------------------------------------------------
// ============================================================================

// ============================================================================
// ----	Public Variables ------------------------------------------------------
// ============================================================================

// ============================================================================
// ----	Public API ------------------------------------------------------------
// ============================================================================

/* in the Microchip way of doing things, you set up processor-common stuff above, then select the
 * appropriate MCU-specific header via a command-line define. for now, while i'm adding support for
 * the MZ EZ board, we'll just copy their method.
 *
 * @todo: refactor MCU selection, board selection, etc. ala AUTOSAR & Linux Kernel.
 */
//#include "processor/ports_processor.h"

#ifdef	__cplusplus
}
#endif

#endif /* PLIB_PORTS_H_ */
