/** @file
 *	@brief	Board Support Package implementation for PIC32MZ Embedded Connectivity (EC) Starter Kit.
 *
 *	Description:
 *	This file contains routines that implement the board support package for
 *	PIC32MZ Embedded Connectivity (EC) Starter Kit.
 *
 *	@note: in my thinking, this file is as close to board customization ala AUTOSAR + Linux Kernel,
 *	as Microchip is likely to get. It's the central location where the various architecture items
 *	are bundled together for the specific board implementation. so, facing "up", the API needs to
 *	stay the same, but facing "down", you make whatever adjustments are necessary to support the
 *	published API.
 *
 *
 *	@note	This file is an as-needed COPY of the file created by Microchip's Harmony Configurator,
 *	v2.04, and/or the tool-created support files (e.g., Peripheral Libs) supplied as part of the
 *	MHC eco system. We have NO intention of stealing code or technology, or of claiming undue
 *	credit. This file is here ONLY during the buildup of support for the PIC32 MZ2048 EFM 144
 *	Starter Kit, what we call the "MZ EZ" board. Eventually, I hope to link directly to Harmony's
 *	code, in a way that allows different target architectures
 *
 *	Anyway, because this is a copy of code generated by a tool owned by Microchip, there is
 *	attribution here but no copyright notice.
 *
 *
 *	Original:
 *	Created on: Dec 27, 2017
 *	Author: kbecker
 *
 *	Current:
 *	$Revision: $
 *	$Date: $
 */

// ============================================================================
// ----	Include Files ---------------------------------------------------------
// ============================================================================

#include "projcfg.h"

// ----	System Headers --------------------------

// ----	Project Headers -------------------------
#include "cwsw_lib.h"

// ----	Module Headers --------------------------
#include "bsp.h"


// ============================================================================
// ----	Constants -------------------------------------------------------------
// ============================================================================

// ============================================================================
// ----	Type Definitions ------------------------------------------------------
// ============================================================================

// ============================================================================
// ----	Global Variables ------------------------------------------------------
// ============================================================================

// ============================================================================
// ----	Module-level Variables ------------------------------------------------
// ============================================================================
static char const * const bsp_RevString = "$Revision: 0123 $";

/* Data Structure:
    switch_port_channel_map[]

  Summary:
    Maps each switch to its port channel

  Description:
    The switch_port_channel_map array, indexed by BSP_SWITCH, maps each switch
    to its port channel.

  Remarks:
    Refer to bsp.h for usage information.
*/
static const PORTS_CHANNEL switch_port_channel_map[] =
{
    PORT_CHANNEL_B,
    PORT_CHANNEL_B,
    PORT_CHANNEL_B
};

/* Data Structure:
    switch_port_bit_pos_map[]

  Summary:
    Maps each switch to its port bit position

  Description:
    The switch_port_bit_pos_map array, indexed by BSP_SWITCH, maps each switch to its port bit position

  Remarks:
    Refer to bsp.h for usage information.
*/
//static const PORTS_BIT_POS switch_port_bit_pos_map[] =
//{
//    PORTS_BIT_POS_12,
//    PORTS_BIT_POS_13,
//    PORTS_BIT_POS_14
//};


// ============================================================================
// ----	Private Prototypes ----------------------------------------------------
// ============================================================================

// ============================================================================
// ----	Public Functions ------------------------------------------------------
// ============================================================================

/* Function:
    void Cwsw_Board__UsbVbusSwitchStateSet(tBrdUsbVbusSwitchState state);

  Summary:
    This function enables or disables the USB VBUS switch on the board.

  Description:
    This function enables or disables the VBUS switch on the board.

  Remarks:
    Refer to bsp_config.h for usage information.
*/
void
Cwsw_Board__UsbVbusSwitchStateSet(tBrdUsbVbusSwitchState state)
{
    /* Enable the VBUS switch */

    PLIB_PORTS_PinWrite( PORTS_ID_0, PORT_CHANNEL_B, PORTS_BIT_POS_5, state );
}


/* Function:
    void BSP_Initialize(void)

  Summary:
    Performs the necessary actions to initialize a board.

  Description:
    This function initializes the LED, Switch and other ports on the board.
    This function must be called by the user before using any APIs present in
    this BSP.

  Remarks:
    Refer to bsp.h for usage information.
*/
void
BSP_Initialize(void)
{
	UNUSED(bsp_RevString);

    /* Setup the USB VBUS Switch Control Pin */
	Cwsw_Board__UsbVbusSwitchStateSet(BSP_USB_VBUS_SWITCH_STATE_DISABLE);
//
//    /* Switch off LEDs */
//    BSP_LEDOff(BSP_LED_1);
//    BSP_LEDOff(BSP_LED_2);
//    BSP_LEDOff(BSP_LED_3);
}
