################################################################################
# Automatically-generated file. Do not edit!
################################################################################

# Add inputs and outputs from these tool invocations to the build variables 
C_SRCS += \
../arch/PIC32MZ2048EFM/framework/decoder/audio_decoders/opus/src/silk/A2NLSF.c \
../arch/PIC32MZ2048EFM/framework/decoder/audio_decoders/opus/src/silk/CNG.c \
../arch/PIC32MZ2048EFM/framework/decoder/audio_decoders/opus/src/silk/HP_variable_cutoff.c \
../arch/PIC32MZ2048EFM/framework/decoder/audio_decoders/opus/src/silk/LPC_analysis_filter.c \
../arch/PIC32MZ2048EFM/framework/decoder/audio_decoders/opus/src/silk/LPC_inv_pred_gain.c \
../arch/PIC32MZ2048EFM/framework/decoder/audio_decoders/opus/src/silk/LP_variable_cutoff.c \
../arch/PIC32MZ2048EFM/framework/decoder/audio_decoders/opus/src/silk/NLSF2A.c \
../arch/PIC32MZ2048EFM/framework/decoder/audio_decoders/opus/src/silk/NLSF_VQ.c \
../arch/PIC32MZ2048EFM/framework/decoder/audio_decoders/opus/src/silk/NLSF_VQ_weights_laroia.c \
../arch/PIC32MZ2048EFM/framework/decoder/audio_decoders/opus/src/silk/NLSF_decode.c \
../arch/PIC32MZ2048EFM/framework/decoder/audio_decoders/opus/src/silk/NLSF_del_dec_quant.c \
../arch/PIC32MZ2048EFM/framework/decoder/audio_decoders/opus/src/silk/NLSF_encode.c \
../arch/PIC32MZ2048EFM/framework/decoder/audio_decoders/opus/src/silk/NLSF_stabilize.c \
../arch/PIC32MZ2048EFM/framework/decoder/audio_decoders/opus/src/silk/NLSF_unpack.c \
../arch/PIC32MZ2048EFM/framework/decoder/audio_decoders/opus/src/silk/NSQ.c \
../arch/PIC32MZ2048EFM/framework/decoder/audio_decoders/opus/src/silk/NSQ_del_dec.c \
../arch/PIC32MZ2048EFM/framework/decoder/audio_decoders/opus/src/silk/PLC.c \
../arch/PIC32MZ2048EFM/framework/decoder/audio_decoders/opus/src/silk/VAD.c \
../arch/PIC32MZ2048EFM/framework/decoder/audio_decoders/opus/src/silk/VQ_WMat_EC.c \
../arch/PIC32MZ2048EFM/framework/decoder/audio_decoders/opus/src/silk/ana_filt_bank_1.c \
../arch/PIC32MZ2048EFM/framework/decoder/audio_decoders/opus/src/silk/biquad_alt.c \
../arch/PIC32MZ2048EFM/framework/decoder/audio_decoders/opus/src/silk/bwexpander.c \
../arch/PIC32MZ2048EFM/framework/decoder/audio_decoders/opus/src/silk/bwexpander_32.c \
../arch/PIC32MZ2048EFM/framework/decoder/audio_decoders/opus/src/silk/check_control_input.c \
../arch/PIC32MZ2048EFM/framework/decoder/audio_decoders/opus/src/silk/code_signs.c \
../arch/PIC32MZ2048EFM/framework/decoder/audio_decoders/opus/src/silk/control_SNR.c \
../arch/PIC32MZ2048EFM/framework/decoder/audio_decoders/opus/src/silk/control_audio_bandwidth.c \
../arch/PIC32MZ2048EFM/framework/decoder/audio_decoders/opus/src/silk/control_codec.c \
../arch/PIC32MZ2048EFM/framework/decoder/audio_decoders/opus/src/silk/debug.c \
../arch/PIC32MZ2048EFM/framework/decoder/audio_decoders/opus/src/silk/dec_API.c \
../arch/PIC32MZ2048EFM/framework/decoder/audio_decoders/opus/src/silk/decode_core.c \
../arch/PIC32MZ2048EFM/framework/decoder/audio_decoders/opus/src/silk/decode_frame.c \
../arch/PIC32MZ2048EFM/framework/decoder/audio_decoders/opus/src/silk/decode_indices.c \
../arch/PIC32MZ2048EFM/framework/decoder/audio_decoders/opus/src/silk/decode_parameters.c \
../arch/PIC32MZ2048EFM/framework/decoder/audio_decoders/opus/src/silk/decode_pitch.c \
../arch/PIC32MZ2048EFM/framework/decoder/audio_decoders/opus/src/silk/decode_pulses.c \
../arch/PIC32MZ2048EFM/framework/decoder/audio_decoders/opus/src/silk/decoder_set_fs.c \
../arch/PIC32MZ2048EFM/framework/decoder/audio_decoders/opus/src/silk/enc_API.c \
../arch/PIC32MZ2048EFM/framework/decoder/audio_decoders/opus/src/silk/encode_indices.c \
../arch/PIC32MZ2048EFM/framework/decoder/audio_decoders/opus/src/silk/encode_pulses.c \
../arch/PIC32MZ2048EFM/framework/decoder/audio_decoders/opus/src/silk/gain_quant.c \
../arch/PIC32MZ2048EFM/framework/decoder/audio_decoders/opus/src/silk/init_decoder.c \
../arch/PIC32MZ2048EFM/framework/decoder/audio_decoders/opus/src/silk/init_encoder.c \
../arch/PIC32MZ2048EFM/framework/decoder/audio_decoders/opus/src/silk/inner_prod_aligned.c \
../arch/PIC32MZ2048EFM/framework/decoder/audio_decoders/opus/src/silk/interpolate.c \
../arch/PIC32MZ2048EFM/framework/decoder/audio_decoders/opus/src/silk/lin2log.c \
../arch/PIC32MZ2048EFM/framework/decoder/audio_decoders/opus/src/silk/log2lin.c \
../arch/PIC32MZ2048EFM/framework/decoder/audio_decoders/opus/src/silk/pitch_est_tables.c \
../arch/PIC32MZ2048EFM/framework/decoder/audio_decoders/opus/src/silk/process_NLSFs.c \
../arch/PIC32MZ2048EFM/framework/decoder/audio_decoders/opus/src/silk/quant_LTP_gains.c \
../arch/PIC32MZ2048EFM/framework/decoder/audio_decoders/opus/src/silk/resampler.c \
../arch/PIC32MZ2048EFM/framework/decoder/audio_decoders/opus/src/silk/resampler_down2.c \
../arch/PIC32MZ2048EFM/framework/decoder/audio_decoders/opus/src/silk/resampler_down2_3.c \
../arch/PIC32MZ2048EFM/framework/decoder/audio_decoders/opus/src/silk/resampler_private_AR2.c \
../arch/PIC32MZ2048EFM/framework/decoder/audio_decoders/opus/src/silk/resampler_private_IIR_FIR.c \
../arch/PIC32MZ2048EFM/framework/decoder/audio_decoders/opus/src/silk/resampler_private_down_FIR.c \
../arch/PIC32MZ2048EFM/framework/decoder/audio_decoders/opus/src/silk/resampler_private_up2_HQ.c \
../arch/PIC32MZ2048EFM/framework/decoder/audio_decoders/opus/src/silk/resampler_rom.c \
../arch/PIC32MZ2048EFM/framework/decoder/audio_decoders/opus/src/silk/shell_coder.c \
../arch/PIC32MZ2048EFM/framework/decoder/audio_decoders/opus/src/silk/sigm_Q15.c \
../arch/PIC32MZ2048EFM/framework/decoder/audio_decoders/opus/src/silk/sort.c \
../arch/PIC32MZ2048EFM/framework/decoder/audio_decoders/opus/src/silk/stereo_LR_to_MS.c \
../arch/PIC32MZ2048EFM/framework/decoder/audio_decoders/opus/src/silk/stereo_MS_to_LR.c \
../arch/PIC32MZ2048EFM/framework/decoder/audio_decoders/opus/src/silk/stereo_decode_pred.c \
../arch/PIC32MZ2048EFM/framework/decoder/audio_decoders/opus/src/silk/stereo_encode_pred.c \
../arch/PIC32MZ2048EFM/framework/decoder/audio_decoders/opus/src/silk/stereo_find_predictor.c \
../arch/PIC32MZ2048EFM/framework/decoder/audio_decoders/opus/src/silk/stereo_quant_pred.c \
../arch/PIC32MZ2048EFM/framework/decoder/audio_decoders/opus/src/silk/sum_sqr_shift.c \
../arch/PIC32MZ2048EFM/framework/decoder/audio_decoders/opus/src/silk/table_LSF_cos.c \
../arch/PIC32MZ2048EFM/framework/decoder/audio_decoders/opus/src/silk/tables_LTP.c \
../arch/PIC32MZ2048EFM/framework/decoder/audio_decoders/opus/src/silk/tables_NLSF_CB_NB_MB.c \
../arch/PIC32MZ2048EFM/framework/decoder/audio_decoders/opus/src/silk/tables_NLSF_CB_WB.c \
../arch/PIC32MZ2048EFM/framework/decoder/audio_decoders/opus/src/silk/tables_gain.c \
../arch/PIC32MZ2048EFM/framework/decoder/audio_decoders/opus/src/silk/tables_other.c \
../arch/PIC32MZ2048EFM/framework/decoder/audio_decoders/opus/src/silk/tables_pitch_lag.c \
../arch/PIC32MZ2048EFM/framework/decoder/audio_decoders/opus/src/silk/tables_pulses_per_block.c 

OBJS += \
./arch/PIC32MZ2048EFM/framework/decoder/audio_decoders/opus/src/silk/A2NLSF.o \
./arch/PIC32MZ2048EFM/framework/decoder/audio_decoders/opus/src/silk/CNG.o \
./arch/PIC32MZ2048EFM/framework/decoder/audio_decoders/opus/src/silk/HP_variable_cutoff.o \
./arch/PIC32MZ2048EFM/framework/decoder/audio_decoders/opus/src/silk/LPC_analysis_filter.o \
./arch/PIC32MZ2048EFM/framework/decoder/audio_decoders/opus/src/silk/LPC_inv_pred_gain.o \
./arch/PIC32MZ2048EFM/framework/decoder/audio_decoders/opus/src/silk/LP_variable_cutoff.o \
./arch/PIC32MZ2048EFM/framework/decoder/audio_decoders/opus/src/silk/NLSF2A.o \
./arch/PIC32MZ2048EFM/framework/decoder/audio_decoders/opus/src/silk/NLSF_VQ.o \
./arch/PIC32MZ2048EFM/framework/decoder/audio_decoders/opus/src/silk/NLSF_VQ_weights_laroia.o \
./arch/PIC32MZ2048EFM/framework/decoder/audio_decoders/opus/src/silk/NLSF_decode.o \
./arch/PIC32MZ2048EFM/framework/decoder/audio_decoders/opus/src/silk/NLSF_del_dec_quant.o \
./arch/PIC32MZ2048EFM/framework/decoder/audio_decoders/opus/src/silk/NLSF_encode.o \
./arch/PIC32MZ2048EFM/framework/decoder/audio_decoders/opus/src/silk/NLSF_stabilize.o \
./arch/PIC32MZ2048EFM/framework/decoder/audio_decoders/opus/src/silk/NLSF_unpack.o \
./arch/PIC32MZ2048EFM/framework/decoder/audio_decoders/opus/src/silk/NSQ.o \
./arch/PIC32MZ2048EFM/framework/decoder/audio_decoders/opus/src/silk/NSQ_del_dec.o \
./arch/PIC32MZ2048EFM/framework/decoder/audio_decoders/opus/src/silk/PLC.o \
./arch/PIC32MZ2048EFM/framework/decoder/audio_decoders/opus/src/silk/VAD.o \
./arch/PIC32MZ2048EFM/framework/decoder/audio_decoders/opus/src/silk/VQ_WMat_EC.o \
./arch/PIC32MZ2048EFM/framework/decoder/audio_decoders/opus/src/silk/ana_filt_bank_1.o \
./arch/PIC32MZ2048EFM/framework/decoder/audio_decoders/opus/src/silk/biquad_alt.o \
./arch/PIC32MZ2048EFM/framework/decoder/audio_decoders/opus/src/silk/bwexpander.o \
./arch/PIC32MZ2048EFM/framework/decoder/audio_decoders/opus/src/silk/bwexpander_32.o \
./arch/PIC32MZ2048EFM/framework/decoder/audio_decoders/opus/src/silk/check_control_input.o \
./arch/PIC32MZ2048EFM/framework/decoder/audio_decoders/opus/src/silk/code_signs.o \
./arch/PIC32MZ2048EFM/framework/decoder/audio_decoders/opus/src/silk/control_SNR.o \
./arch/PIC32MZ2048EFM/framework/decoder/audio_decoders/opus/src/silk/control_audio_bandwidth.o \
./arch/PIC32MZ2048EFM/framework/decoder/audio_decoders/opus/src/silk/control_codec.o \
./arch/PIC32MZ2048EFM/framework/decoder/audio_decoders/opus/src/silk/debug.o \
./arch/PIC32MZ2048EFM/framework/decoder/audio_decoders/opus/src/silk/dec_API.o \
./arch/PIC32MZ2048EFM/framework/decoder/audio_decoders/opus/src/silk/decode_core.o \
./arch/PIC32MZ2048EFM/framework/decoder/audio_decoders/opus/src/silk/decode_frame.o \
./arch/PIC32MZ2048EFM/framework/decoder/audio_decoders/opus/src/silk/decode_indices.o \
./arch/PIC32MZ2048EFM/framework/decoder/audio_decoders/opus/src/silk/decode_parameters.o \
./arch/PIC32MZ2048EFM/framework/decoder/audio_decoders/opus/src/silk/decode_pitch.o \
./arch/PIC32MZ2048EFM/framework/decoder/audio_decoders/opus/src/silk/decode_pulses.o \
./arch/PIC32MZ2048EFM/framework/decoder/audio_decoders/opus/src/silk/decoder_set_fs.o \
./arch/PIC32MZ2048EFM/framework/decoder/audio_decoders/opus/src/silk/enc_API.o \
./arch/PIC32MZ2048EFM/framework/decoder/audio_decoders/opus/src/silk/encode_indices.o \
./arch/PIC32MZ2048EFM/framework/decoder/audio_decoders/opus/src/silk/encode_pulses.o \
./arch/PIC32MZ2048EFM/framework/decoder/audio_decoders/opus/src/silk/gain_quant.o \
./arch/PIC32MZ2048EFM/framework/decoder/audio_decoders/opus/src/silk/init_decoder.o \
./arch/PIC32MZ2048EFM/framework/decoder/audio_decoders/opus/src/silk/init_encoder.o \
./arch/PIC32MZ2048EFM/framework/decoder/audio_decoders/opus/src/silk/inner_prod_aligned.o \
./arch/PIC32MZ2048EFM/framework/decoder/audio_decoders/opus/src/silk/interpolate.o \
./arch/PIC32MZ2048EFM/framework/decoder/audio_decoders/opus/src/silk/lin2log.o \
./arch/PIC32MZ2048EFM/framework/decoder/audio_decoders/opus/src/silk/log2lin.o \
./arch/PIC32MZ2048EFM/framework/decoder/audio_decoders/opus/src/silk/pitch_est_tables.o \
./arch/PIC32MZ2048EFM/framework/decoder/audio_decoders/opus/src/silk/process_NLSFs.o \
./arch/PIC32MZ2048EFM/framework/decoder/audio_decoders/opus/src/silk/quant_LTP_gains.o \
./arch/PIC32MZ2048EFM/framework/decoder/audio_decoders/opus/src/silk/resampler.o \
./arch/PIC32MZ2048EFM/framework/decoder/audio_decoders/opus/src/silk/resampler_down2.o \
./arch/PIC32MZ2048EFM/framework/decoder/audio_decoders/opus/src/silk/resampler_down2_3.o \
./arch/PIC32MZ2048EFM/framework/decoder/audio_decoders/opus/src/silk/resampler_private_AR2.o \
./arch/PIC32MZ2048EFM/framework/decoder/audio_decoders/opus/src/silk/resampler_private_IIR_FIR.o \
./arch/PIC32MZ2048EFM/framework/decoder/audio_decoders/opus/src/silk/resampler_private_down_FIR.o \
./arch/PIC32MZ2048EFM/framework/decoder/audio_decoders/opus/src/silk/resampler_private_up2_HQ.o \
./arch/PIC32MZ2048EFM/framework/decoder/audio_decoders/opus/src/silk/resampler_rom.o \
./arch/PIC32MZ2048EFM/framework/decoder/audio_decoders/opus/src/silk/shell_coder.o \
./arch/PIC32MZ2048EFM/framework/decoder/audio_decoders/opus/src/silk/sigm_Q15.o \
./arch/PIC32MZ2048EFM/framework/decoder/audio_decoders/opus/src/silk/sort.o \
./arch/PIC32MZ2048EFM/framework/decoder/audio_decoders/opus/src/silk/stereo_LR_to_MS.o \
./arch/PIC32MZ2048EFM/framework/decoder/audio_decoders/opus/src/silk/stereo_MS_to_LR.o \
./arch/PIC32MZ2048EFM/framework/decoder/audio_decoders/opus/src/silk/stereo_decode_pred.o \
./arch/PIC32MZ2048EFM/framework/decoder/audio_decoders/opus/src/silk/stereo_encode_pred.o \
./arch/PIC32MZ2048EFM/framework/decoder/audio_decoders/opus/src/silk/stereo_find_predictor.o \
./arch/PIC32MZ2048EFM/framework/decoder/audio_decoders/opus/src/silk/stereo_quant_pred.o \
./arch/PIC32MZ2048EFM/framework/decoder/audio_decoders/opus/src/silk/sum_sqr_shift.o \
./arch/PIC32MZ2048EFM/framework/decoder/audio_decoders/opus/src/silk/table_LSF_cos.o \
./arch/PIC32MZ2048EFM/framework/decoder/audio_decoders/opus/src/silk/tables_LTP.o \
./arch/PIC32MZ2048EFM/framework/decoder/audio_decoders/opus/src/silk/tables_NLSF_CB_NB_MB.o \
./arch/PIC32MZ2048EFM/framework/decoder/audio_decoders/opus/src/silk/tables_NLSF_CB_WB.o \
./arch/PIC32MZ2048EFM/framework/decoder/audio_decoders/opus/src/silk/tables_gain.o \
./arch/PIC32MZ2048EFM/framework/decoder/audio_decoders/opus/src/silk/tables_other.o \
./arch/PIC32MZ2048EFM/framework/decoder/audio_decoders/opus/src/silk/tables_pitch_lag.o \
./arch/PIC32MZ2048EFM/framework/decoder/audio_decoders/opus/src/silk/tables_pulses_per_block.o 

C_DEPS += \
./arch/PIC32MZ2048EFM/framework/decoder/audio_decoders/opus/src/silk/A2NLSF.d \
./arch/PIC32MZ2048EFM/framework/decoder/audio_decoders/opus/src/silk/CNG.d \
./arch/PIC32MZ2048EFM/framework/decoder/audio_decoders/opus/src/silk/HP_variable_cutoff.d \
./arch/PIC32MZ2048EFM/framework/decoder/audio_decoders/opus/src/silk/LPC_analysis_filter.d \
./arch/PIC32MZ2048EFM/framework/decoder/audio_decoders/opus/src/silk/LPC_inv_pred_gain.d \
./arch/PIC32MZ2048EFM/framework/decoder/audio_decoders/opus/src/silk/LP_variable_cutoff.d \
./arch/PIC32MZ2048EFM/framework/decoder/audio_decoders/opus/src/silk/NLSF2A.d \
./arch/PIC32MZ2048EFM/framework/decoder/audio_decoders/opus/src/silk/NLSF_VQ.d \
./arch/PIC32MZ2048EFM/framework/decoder/audio_decoders/opus/src/silk/NLSF_VQ_weights_laroia.d \
./arch/PIC32MZ2048EFM/framework/decoder/audio_decoders/opus/src/silk/NLSF_decode.d \
./arch/PIC32MZ2048EFM/framework/decoder/audio_decoders/opus/src/silk/NLSF_del_dec_quant.d \
./arch/PIC32MZ2048EFM/framework/decoder/audio_decoders/opus/src/silk/NLSF_encode.d \
./arch/PIC32MZ2048EFM/framework/decoder/audio_decoders/opus/src/silk/NLSF_stabilize.d \
./arch/PIC32MZ2048EFM/framework/decoder/audio_decoders/opus/src/silk/NLSF_unpack.d \
./arch/PIC32MZ2048EFM/framework/decoder/audio_decoders/opus/src/silk/NSQ.d \
./arch/PIC32MZ2048EFM/framework/decoder/audio_decoders/opus/src/silk/NSQ_del_dec.d \
./arch/PIC32MZ2048EFM/framework/decoder/audio_decoders/opus/src/silk/PLC.d \
./arch/PIC32MZ2048EFM/framework/decoder/audio_decoders/opus/src/silk/VAD.d \
./arch/PIC32MZ2048EFM/framework/decoder/audio_decoders/opus/src/silk/VQ_WMat_EC.d \
./arch/PIC32MZ2048EFM/framework/decoder/audio_decoders/opus/src/silk/ana_filt_bank_1.d \
./arch/PIC32MZ2048EFM/framework/decoder/audio_decoders/opus/src/silk/biquad_alt.d \
./arch/PIC32MZ2048EFM/framework/decoder/audio_decoders/opus/src/silk/bwexpander.d \
./arch/PIC32MZ2048EFM/framework/decoder/audio_decoders/opus/src/silk/bwexpander_32.d \
./arch/PIC32MZ2048EFM/framework/decoder/audio_decoders/opus/src/silk/check_control_input.d \
./arch/PIC32MZ2048EFM/framework/decoder/audio_decoders/opus/src/silk/code_signs.d \
./arch/PIC32MZ2048EFM/framework/decoder/audio_decoders/opus/src/silk/control_SNR.d \
./arch/PIC32MZ2048EFM/framework/decoder/audio_decoders/opus/src/silk/control_audio_bandwidth.d \
./arch/PIC32MZ2048EFM/framework/decoder/audio_decoders/opus/src/silk/control_codec.d \
./arch/PIC32MZ2048EFM/framework/decoder/audio_decoders/opus/src/silk/debug.d \
./arch/PIC32MZ2048EFM/framework/decoder/audio_decoders/opus/src/silk/dec_API.d \
./arch/PIC32MZ2048EFM/framework/decoder/audio_decoders/opus/src/silk/decode_core.d \
./arch/PIC32MZ2048EFM/framework/decoder/audio_decoders/opus/src/silk/decode_frame.d \
./arch/PIC32MZ2048EFM/framework/decoder/audio_decoders/opus/src/silk/decode_indices.d \
./arch/PIC32MZ2048EFM/framework/decoder/audio_decoders/opus/src/silk/decode_parameters.d \
./arch/PIC32MZ2048EFM/framework/decoder/audio_decoders/opus/src/silk/decode_pitch.d \
./arch/PIC32MZ2048EFM/framework/decoder/audio_decoders/opus/src/silk/decode_pulses.d \
./arch/PIC32MZ2048EFM/framework/decoder/audio_decoders/opus/src/silk/decoder_set_fs.d \
./arch/PIC32MZ2048EFM/framework/decoder/audio_decoders/opus/src/silk/enc_API.d \
./arch/PIC32MZ2048EFM/framework/decoder/audio_decoders/opus/src/silk/encode_indices.d \
./arch/PIC32MZ2048EFM/framework/decoder/audio_decoders/opus/src/silk/encode_pulses.d \
./arch/PIC32MZ2048EFM/framework/decoder/audio_decoders/opus/src/silk/gain_quant.d \
./arch/PIC32MZ2048EFM/framework/decoder/audio_decoders/opus/src/silk/init_decoder.d \
./arch/PIC32MZ2048EFM/framework/decoder/audio_decoders/opus/src/silk/init_encoder.d \
./arch/PIC32MZ2048EFM/framework/decoder/audio_decoders/opus/src/silk/inner_prod_aligned.d \
./arch/PIC32MZ2048EFM/framework/decoder/audio_decoders/opus/src/silk/interpolate.d \
./arch/PIC32MZ2048EFM/framework/decoder/audio_decoders/opus/src/silk/lin2log.d \
./arch/PIC32MZ2048EFM/framework/decoder/audio_decoders/opus/src/silk/log2lin.d \
./arch/PIC32MZ2048EFM/framework/decoder/audio_decoders/opus/src/silk/pitch_est_tables.d \
./arch/PIC32MZ2048EFM/framework/decoder/audio_decoders/opus/src/silk/process_NLSFs.d \
./arch/PIC32MZ2048EFM/framework/decoder/audio_decoders/opus/src/silk/quant_LTP_gains.d \
./arch/PIC32MZ2048EFM/framework/decoder/audio_decoders/opus/src/silk/resampler.d \
./arch/PIC32MZ2048EFM/framework/decoder/audio_decoders/opus/src/silk/resampler_down2.d \
./arch/PIC32MZ2048EFM/framework/decoder/audio_decoders/opus/src/silk/resampler_down2_3.d \
./arch/PIC32MZ2048EFM/framework/decoder/audio_decoders/opus/src/silk/resampler_private_AR2.d \
./arch/PIC32MZ2048EFM/framework/decoder/audio_decoders/opus/src/silk/resampler_private_IIR_FIR.d \
./arch/PIC32MZ2048EFM/framework/decoder/audio_decoders/opus/src/silk/resampler_private_down_FIR.d \
./arch/PIC32MZ2048EFM/framework/decoder/audio_decoders/opus/src/silk/resampler_private_up2_HQ.d \
./arch/PIC32MZ2048EFM/framework/decoder/audio_decoders/opus/src/silk/resampler_rom.d \
./arch/PIC32MZ2048EFM/framework/decoder/audio_decoders/opus/src/silk/shell_coder.d \
./arch/PIC32MZ2048EFM/framework/decoder/audio_decoders/opus/src/silk/sigm_Q15.d \
./arch/PIC32MZ2048EFM/framework/decoder/audio_decoders/opus/src/silk/sort.d \
./arch/PIC32MZ2048EFM/framework/decoder/audio_decoders/opus/src/silk/stereo_LR_to_MS.d \
./arch/PIC32MZ2048EFM/framework/decoder/audio_decoders/opus/src/silk/stereo_MS_to_LR.d \
./arch/PIC32MZ2048EFM/framework/decoder/audio_decoders/opus/src/silk/stereo_decode_pred.d \
./arch/PIC32MZ2048EFM/framework/decoder/audio_decoders/opus/src/silk/stereo_encode_pred.d \
./arch/PIC32MZ2048EFM/framework/decoder/audio_decoders/opus/src/silk/stereo_find_predictor.d \
./arch/PIC32MZ2048EFM/framework/decoder/audio_decoders/opus/src/silk/stereo_quant_pred.d \
./arch/PIC32MZ2048EFM/framework/decoder/audio_decoders/opus/src/silk/sum_sqr_shift.d \
./arch/PIC32MZ2048EFM/framework/decoder/audio_decoders/opus/src/silk/table_LSF_cos.d \
./arch/PIC32MZ2048EFM/framework/decoder/audio_decoders/opus/src/silk/tables_LTP.d \
./arch/PIC32MZ2048EFM/framework/decoder/audio_decoders/opus/src/silk/tables_NLSF_CB_NB_MB.d \
./arch/PIC32MZ2048EFM/framework/decoder/audio_decoders/opus/src/silk/tables_NLSF_CB_WB.d \
./arch/PIC32MZ2048EFM/framework/decoder/audio_decoders/opus/src/silk/tables_gain.d \
./arch/PIC32MZ2048EFM/framework/decoder/audio_decoders/opus/src/silk/tables_other.d \
./arch/PIC32MZ2048EFM/framework/decoder/audio_decoders/opus/src/silk/tables_pitch_lag.d \
./arch/PIC32MZ2048EFM/framework/decoder/audio_decoders/opus/src/silk/tables_pulses_per_block.d 


# Each subdirectory must supply rules for building sources it contributes
arch/PIC32MZ2048EFM/framework/decoder/audio_decoders/opus/src/silk/%.o: ../arch/PIC32MZ2048EFM/framework/decoder/audio_decoders/opus/src/silk/%.c
	@echo 'Building file: $<'
	@echo 'Invoking: GCC C Compiler'
	gcc -std=gnu11 -D"XPRJ_Debug_Win_MinGW=1" -I"C:/Users/kbecker/_projects/PersonalDev/cwsw_lib/components/cwsw_clock_prj/cwsw_lib/include" -I"C:/Users/kbecker/_projects/PersonalDev/cwsw_lib/components/cwsw_clock_prj/ut" -I"C:/Users/kbecker/_projects/PersonalDev/cwsw_lib/components/cwsw_clock_prj/cwsw_clock/include" -I"C:/Users/kbecker/_projects/PersonalDev/cwsw_lib/components/cwsw_clock_prj/cwsw_bsp/include" -I"C:/Users/kbecker/_projects/PersonalDev/cwsw_lib/components/cwsw_clock_prj/arch/PIC32MZ2048EFM/framework" -I"C:/Users/kbecker/_projects/PersonalDev/cwsw_lib/components/cwsw_clock_prj/arch/PIC32MZ2048EFM/framework/system/common" -I"C:/Users/kbecker/_projects/PersonalDev/cwsw_lib/components/cwsw_clock_prj/arch/PIC32MZ2048EFM/app/system_config/bsp" -I"C:/Users/kbecker/_projects/PersonalDev/cwsw_lib/components/cwsw_clock_prj/arch/PIC32MZ2048EFM/app/system_config/framework" -I"C:/Users/kbecker/_projects/PersonalDev/cwsw_lib/components/cwsw_clock_prj/arch/PIC32MZ2048EFM/app/system_config/framework/system/devcon" -I"C:/Users/kbecker/_projects/PersonalDev/cwsw_lib/components/cwsw_clock_prj/arch/PIC32MZ2048EFM/app/system_config" -O0 -g3 -pedantic -Wall -Wextra -Wconversion -c -fmessage-length=0 -MMD -MP -MF"$(@:%.o=%.d)" -MT"$(@)" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '


