/** @file
 *	@brief	One-sentence short description of file.
 *
 *	Description:
 *
 *
 *	@note	This file is an as-needed COPY of the file created by Microchip's Harmony Configurator,
 *	v2.04, and/or the tool-created support files (e.g., Peripheral Libs) supplied as part of the
 *	MHC eco system. We have NO intention of stealing code or technology, or of claiming undue
 *	credit. This file is here ONLY during the buildup of support for the PIC32 MZ2048 EFM 144
 *	Starter Kit, what we call the "MZ EZ" board. Eventually, I hope to link directly to Harmony's
 *	code, in a way that allows different target architectures
 *
 *	Anyway, because this is a copy of code generated by a tool owned by Microchip, there is
 *	attribution here but no copyright notice.
 *
 *
 *	Original:
 *	Created on: Dec 21, 2017
 *	Author: kbecker
 *
 *	Current:
 *	$Revision: $
 *	$Date: $
 */

#ifndef CWSW_BSP_CWSW_BSP_H_
#define CWSW_BSP_CWSW_BSP_H_

#ifdef	__cplusplus
extern "C" {
#endif

// ============================================================================
// ----	Include Files ---------------------------------------------------------
// ============================================================================

#include "projcfg.h"

// ----	System Headers --------------------------

// ----	Project Headers -------------------------
#include "cwsw_lib.h"

// ----	Module Headers --------------------------


// ============================================================================
// ----	Constants -------------------------------------------------------------
// ============================================================================
#define BSP_CWSW_BSP_H__REVSTRING "$Revision: 0123 $"

/** Logical values for the LEDs. note the actual wiring on the board, or the polarity of the
 * driver, might be inverted; that connection is made at the board level, not the bsp level.
 */
enum eDO_Logical_Values { kLogicalOff, kLogicalOn };


// ============================================================================
// ----	Type Definitions ------------------------------------------------------
// ============================================================================

typedef enum eDO_Logical_Values		tDO_LogicalValues;


// ============================================================================
// ----	Public Variables ------------------------------------------------------
// ============================================================================

// ============================================================================
// ----	Public API ------------------------------------------------------------
// ============================================================================

extern uint16_t BSP__Init(void);


#ifdef	__cplusplus
}
#endif

#endif /* CWSW_BSP_CWSW_BSP_H_ */
