/** @file
 *	@brief	Clock System Service implementation.
 *
 *	Description:
 *	The Clock System Service provides a simple interface to manage the clock
 *	on Microchip microcontrollers. This file implements the core interface routines
 *	for the Clock System Service. While building the system service from source,
 *	ALWAYS include this file in the build.
 *
 *
 *	@note	This file is an as-needed COPY of the file created by Microchip's Harmony Configurator,
 *	v2.04, and/or the tool-created support files (e.g., Peripheral Libs) supplied as part of the
 *	MHC eco system. We have NO intention of stealing code or technology, or of claiming undue
 *	credit. This file is here ONLY during the buildup of support for the PIC32 MZ2048 EFM 144
 *	Starter Kit, what we call the "MZ EZ" board. Eventually, I hope to link directly to Harmony's
 *	code, in a way that allows different target architectures
 *
 *	Anyway, because this is a copy of code generated by a tool owned by Microchip, there is
 *	attribution here but no copyright notice.
 *
 *
 *	Original:
 *	Created on: Dec 26, 2017
 *	Author: kbecker
 *
 *	Current:
 *	$Revision: $
 *	$Date: $
 */

// ============================================================================
// ----	Include Files ---------------------------------------------------------
// ============================================================================

#include "projcfg.h"

// ----	System Headers --------------------------

// ----	Project Headers -------------------------
#include "../../../../../../cwsw_arch/pic32mz/framework/system/clk/src/sys_clk_local.h"

// ----	Module Headers --------------------------


// ============================================================================
// ----	Constants -------------------------------------------------------------
// ============================================================================

// ============================================================================
// ----	Type Definitions ------------------------------------------------------
// ============================================================================

// ============================================================================
// ----	Global Variables ------------------------------------------------------
// ============================================================================

SYS_CLK_OBJECT clkObject;


// ============================================================================
// ----	Module-level Variables ------------------------------------------------
// ============================================================================
static char const * const src_clk_RevString = "$Revision: 0123 $";


// ============================================================================
// ----	Private Prototypes ----------------------------------------------------
// ============================================================================

// ============================================================================
// ----	Public Functions ------------------------------------------------------
// ============================================================================

/******************************************************************************
  Function:
    void SYS_CLK_Initialize ( const SYS_CLK_INIT *clkInit )

  Summary:
    Initializes hardware and internal data structure for the general features
    of the clock.

  Description:
    This function initializes hardware and internal data structure for the general
    features of the clock. Preferably, this API should be called early in the
    initialization (before other modules are initialized so that the clock gets
    the necessary settling time before normal execution of the code starts).

  Remarks:
    None.
*/
#include "osc/plib_osc.h"		/* klb: PLIB_OSC_CurrentSysClockGet() */
void SYS_CLK_Initialize(const SYS_CLK_INIT *clkInit) {
	CLK_SOURCES_SYSTEM systemSource;
	uint32_t clockClosest = 0;

    UNUSED(src_clk_RevString);

    /* If the user has not passed anything that means he want to retain the
     * configuration bit settings  */
    if ( clkInit != NULL )
    {
//        systemSource = _SYS_CLK_ClockTypeMap(PLIB_OSC_CurrentSysClockGet ( OSC_PLIB_ID ));
//        if(!_SYS_CLK_SystemClockSet(systemSource, clkInit->systemClockFrequencyHz, clkInit->waitTillComplete, &clockClosest))
        {

        }
		#if(0)

            SYS_ASSERT(false, "Critical failure when setting system clock");
            return;
		#endif
        #if defined(PLIB_OSC_ExistsOnWaitAction)
        if ( PLIB_OSC_ExistsOnWaitAction ( OSC_PLIB_ID ) )
        {
            /* Sets the oscillator's response to a 'Wait' instruction */
            PLIB_OSC_OnWaitActionSet ( OSC_PLIB_ID, clkInit->onWaitInstruction );
        }
        #endif
    }
    else
    {
        clkObject.systemClock = _SYS_CLK_SystemClockRead();
    }

    clkObject.callback = NULL;
}


/******************************************************************************
  Function:
    uint32_t SYS_CLK_SystemFrequencyGet ( void )

  Summary:
    Gets the system clock frequency in Hertz.

  Description:
    This function gets the System clock frequency in Hertz.

  Remarks:
    None.
*/
uint32_t SYS_CLK_SystemFrequencyGet(void) {
    return clkObject.systemClock;
}


